name = "fundaclass-worker"
type = "javascript"

account_id = "e88632aaffcdc561e71b2aa9c33ef19c"
workers_dev = true
route = "fundaclass.eu.org/*"
zone_id = "YOUR_CLOUDFLARE_ZONE_ID"

main = "index.js"  # 🔹 Add this line to specify the entry script

[build]
command = ""

[miniflare]
kv_persist = true
